const Get = require('../models/addGame.js');
const db = require('./db.js');

exports.populateListOfGames = async (listOfGames) => {
  var errors = [];
  for (let game of listOfGames) {
    try {
      var data = await Get.getAllGameDetails(game);
      if (data.error) {
        errors.push(data);
      } else {
        await Get.insertGameImageAndCategories(data)
      }
    } catch (error) {
      console.log('error in populate list of games');
      errors.push(error);
    }
  }
  return errors;
};

exports.populateBoardGames = async () => {
  var uniqueBoardGames = [];
  for (let name of testTwo) {
    if (!uniqueBoardGames.includes(name)) {
      uniqueBoardGames.push(name);
    }
  }
  var currentFirstIndex = 0;
  var currentLastIndex = 10;
  var errors = [];
  while (currentFirstIndex < uniqueBoardGames.length) {
    var currentListOfGames = uniqueBoardGames.slice(currentFirstIndex, currentLastIndex);
    var e = await exports.populateListOfGames(currentListOfGames)
    errors = [...errors, ...e];
    currentFirstIndex += 10;
    currentLastIndex += 10;
  }
  console.log('finished');
  console.log(errors);
}





const nanErrors = [
  'Tâb', 'Tri-nim', 'Sho', 'Okey', 'Chapayev', 'Carrom', 'Thayaam'
]


const testOne = [
  "A Game of War",
  "Abalone",
  "18XX",
  "Asalto",
  "Backgammon",
  "BattleLore"
]

const minimal = [
  "A Game of War",
  "Abalone",
  "Agon",
  "Android: Netrunner",
  "Arimaa",
  "Asalto",
  "Backgammon",
  "BattleLore",
  "Battleship"
]

const boardGames = [
  // Strategy games
  "A Game of War",
  "Abalone",
  "Agon",
  "Android: Netrunner",
  "Arimaa",
  "Asalto",
  "Backgammon",
  "BattleLore",
  "Battleship",
  "Blood Bowl",
  "Bul",
  "Camelot",
  "Chaturanga (Indian chess)",
  "Checkers",
  "Chess",
  "Commands & Colors: Ancients",
  "Connect Four",
  "Connect6",
  "Cross and circle game",
  "Daldøs",
  "Diamond",
  "Diceball!",
  "Doublets",
  "Downfall",
  "DVONN",
  "Draughts",
  "English Game",
  "Fanorona",
  "Game of the Generals",
  "Ghosts",
  "GIPF",
  "Go",
  "Gobblet",
  "Gomoku",
  "Guess Who?",
  "Hare and Hounds",
  "Hounds and Jackals",
  "Hex",
  "Hijara",
  "Irish",
  "Jacquet",
  "Janggi (Korean chess)",
  "Jaipur",
  "Kalah",
  "Kamisado",
  "Khet",
  "Liubo",
  "Lost Cities",
  "Mad Gab",
  "Makruk (Thai chess)",
  "Mastermind",
  "Matching game",
  "Nine men's morris",
  "Onyx",
  "Operation",
  "Ouk-Khmer (Cambodian chess)",
  "Oware",
  "Plateau",
  "PÜNCT",
  "Quarto",
  "Qwirkle",
  "Reversi (Othello)",
  "Rithmomachy",
  "RSVP",
  "Sáhkku",
  "Santorini",
  "Sector 41",
  "Senet",
  "Shatar (Mongolian chess)",
  "Shatranj (Persian chess)",
  "Shogi (Japanese chess)",
  "Simon",
  "Sittuyin (Burmese chess)",
  "Skip-Bo",
  "Space Hulk",
  "Star Wars: X-Wing Miniatures Game",
  "Stratego",
  "Suffragetto",
  "Sugoroku",
  "Summoner Wars (Second Edition)",
  "Ta Yü",
  "Tâb",
  "Tafl (Tablut)",
  "Tantrix",
  "Tak",
  "Twilight Struggle: The Cold War, 1945–1989",
  "Verquere",
  "Xiangqi (Chinese chess)",
  "YINSH",
  "ZÈRTZ",
  // Multi-player elimination board games
  // Participants are typically eliminated before game end.
  "13 Dead End Drive",
  "1313 Dead End Drive",
  "American Megafauna",
  "Anti-Monopoly",
  "Attack!",
  "Axis & Allies",
  "Bang!",
  "Battle Sheep",
  "Betrayal at House on the Hill",
  "Blokus",
  "Blood Feud in New York",
  "Blue Max",
  "Bookchase",
  "Castle Risk",
  "Clue Jr.: Case of the Missing Pet",
  "Coppit",
  "Diplomacy",
  "Djambi",
  "Doom: The Boardgame",
  "Eclipse: New Dawn for the Galaxy",
  "The Farming Game",
  "Finance",
  "Ghettopoly",
  "Glückshaus",
  "The Great Train Robbery",
  "Heroscape",
  "Hey, That's My Fish!",
  "Hotel",
  "Jenga",
  "King of Tokyo",
  "King Oil",
  "Ludo",
  "Mikado",
  "Monopoly",
  "Poleconomy",
  "Risk",
  "Shadow Hunters",
  "Shengguan Tu",
  "Shogun/Samurai Swords",
  "Solarquest",
  "Spy Alley",
  "Star Wars Epic Duels",
  "Star Wars Tactics",
  "StarCraft: The Board Game",
  "Strange Synergy",
  "Summit",
  "TEG",
  "Terakh",
  "Titan",
  "Tri-nim",
  "Tsuro",
  "Tsuro of the Seas",
  "War on Terror, The Boardgame",
  // European race games
  "Cartagena",
  "Chicken Cha Cha Cha",
  "Formula D",
  "Game of the Goose",
  "Hare and Tortoise",
  "Mississippi Queen",
  "Transformers",
  // Multiplayer games without elimination
  // Everyone can play along to the end. These games are especially suited for mixed play with adults and children.
  "18XX",
  "221B Baker Street: The Master Detective Game",
  "30 Seconds",
  "About Time",
  "Acquire",
  "Acronymble",
  "Afrikan tähti",
  "Agricola",
  "Air Charter",
  "Aksharit",
  "Aladdin's Dragons",
  "Alhambra",
  "Alias",
  "Amun-Re",
  "Arkham Horror",
  "Articulate!",
  "Auf Achse",
  "Australia",
  "Azul",
  "Bailout! The Game",
  "Balderdash",
  "Barbarossa",
  "Battlestar Galactica",
  "Bezzerwizzer",
  "Blankety Blank",
  "Blood Rage",
  "Bonkers!",
  "Brain Chain",
  "Buccaneer",
  "Camel Up",
  "Candy Land",
  "Can't Stop",
  "Capitol",
  "Carcassonne",
  "Careers",
  "Caribbean",
  "Cartagena",
  "Caylus",
  "Chinese checkers (Sternhalma)",
  "Chowka bhara",
  "Chromino",
  "CirKis",
  "Civilization",
  "Clans",
  "Clue/Cluedo",
  "Codenames",
  "Coin Hopping—Washington D.C.",
  "Colt Express",
  "Concept",
  "Conspiracy",
  "Continuo",
  "Cosmic Encounter",
  "Catan (The Settlers of Catan)",
  "Cranium",
  "Crosstrack",
  "Dark Tower",
  "Dead of Winter: A Cross Roads Game",
  "Diamant",
  "Dixit",
  "Dominion",
  "Don't Miss the Boat",
  "Don't Quote Me",
  "Dorn",
  "Drunter und Drüber",
  "Dune",
  "Dungeons & Dragons",
  "El Grande",
  "Elfenland",
  "Enchanted Forest",
  "Entdecker",
  "Everdell",
  "Escape from Atlantis",
  "A Feast for Odin",
  "Fictionary",
"Axis and Allies",
  "Axis and Allies D-Day",
  "Axis and Allies Europe",
  "Aeroplanes: Aviation Ascendant",
  "Chebache",
  "Chinese Checkers",
  "Crash Tackle",
  "Dover Patrol",
  "Dracula's Revenge",
  "Frankenstein's Children",
  "Hedbanz",
  "Isis & Osiris",
  "L'Attaque",
  "Mage Stones",
  "Malaika",
  "Mancala",
  "Mind Mover",
  "Mojo",
  "Mozaic",
  "Nabuko Generals and Conquerors",
  "Obsession",
  "Patolli",
  "Quatro",
  "Quirky",
  "Rhumb Line",
  "Serpentine",
  "Sho",
  "Space Hulk",
  "Strange Synergy",
  "Summit",
  "TEG - Plan Táctico y Estratégico de la Guerra",
  "Titan",
  "War on Terror",
  "Backgammon",
  "Battleship",
  "Blokus",
  "Blood Bowl",
  "Blue Moon",
  "Bul",
  "Checkers",
  "Chess",
  "Chinese Checkers",
  "Crash Tackle",
  "Daldos",
  "Dover Patrol",
  "Dracula's Revenge",
  "Downfall",
  "Fanorona",
  "Frankenstein's Children",
  "Ghosts",
  "Go",
  "Guess Who?",
  "Hedbanz",
  "Hijara",
  "Isis & Osiris",
  "Kamisado",
  "Kingdoms",
  "L'Attaque",
  "Liubo",
  "Lord of the Rings",
  "Mage Stones",
  "Malaika",
  "Mancala",
  "Mastermind",
  "Mind Mover",
  "Mojo",
  "Mozaic",
  "Nabuko Generals and Conquerors",
  "Obsession",
  "Patolli",
  "Plateau",
  "Quatro",
  "Quirky",
  "Reversi",
  "Rhumb Line",
  "Sáhkku",
  "Senet",
  "Serpentine",
  "The Settlers of Catan",
  "Sho",
  "Sorry",
  "Space Hulk",
  "Star Wars Epic Duels",
  "Stratego",
  "Sugoroku",
  "Tâb",
  "Tantrix",
  "Thayaam",
  "Tri Tactics",
  "Wari",
  "Zambezy",
  "Privateer",
  "Risk",
  "Solarquest",
  "Star Wars X-Wing Miniatures",
  "Strange Synergy",
  "Figure It Out",
"Fireball Island",
"Focus",
"Fresco",
"Game For Fame",
"The Game of Life",
"Gift Trap",
"Giganten",
"Girl Talk",
"The Great Train Robbery",
"GridIron Master",
"Halma",
"History of the World",
"Hoity Toity",
"Hooop!",
"Hūsker Dū?",
"I'm the Boss!",
"Imperial",
"Indigo",
"Ingenious",
"Inkan aarre",
"Java",
"Journey Through Europe",
"Junta",
"Karuba",
"Keltis",
"Kill Doctor Lucky",
"Kingdomino",
"Kingdoms",
"Labyrinth",
"Landslide",
"Las Vegas",
"Le Havre",
"The LOGO Board Game",
"The London Game",
"Lords of Waterdeep",
"Löwenherz",
"Luck of the Draw",
"Die Macher",
"The Mad Magazine Game",
"The Magic Labyrinth",
"Mahjong",
"Malefiz",
"Mall Madness",
"Manhattan",
"Masterpiece",
"Medici",
"Medina",
"Mensch ärgere Dich nicht",
"Merchant of Venus",
"Metro",
"Mexica",
"Mine a Million",
"Modern Art",
"Mutant Meeples",
"Near and Far",
"Niagara",
"Okey",
"Omega Virus",
"Ouija",
"Outrage!",
"Pack & Stack",
"Pank-a-Squith",
"Parcheesi",
"Parqués",
"Pay Day",
"Personal Preference",
"Pictionary",
"Pirate's Cove",
"Power Grid",
"Primordial Soup",
"The Princes of Florence",
"Probe",
"Puerto Rico",
"Puzzle",
"Qin",
"The Quest of the Philosopher's Stone",
"Quoridor",
"Qwirkle",
"Ra",
"Rail Baron",
"Railway Rivals",
"Ricochet Robots",
"Rivers, Roads & Rails",
"RoboRally",
"Rummikub",
"Rummoli",
"Saint Petersburg",
"Samurai",
"San Marco",
"Scattergories",
"Scene It?",
"Scotland Yard",
"Scoundrels of Skullport",
"Scrabble",
"Scythe",
"Sequence",
"Shadows over Camelot",
"Sherlock Holmes: Consulting Detective",
"Skirrid",
"Small World",
"Snakes and Ladders",
"Sorry!",
"Splendor",
"Squatter",
"Stock Ticker",
"Taj Mahal",
"Take It Easy",
"Take the Galaxy",
"Terraforming Mars",
"Terra Mystica",
"Through the Ages: A Story of Civilization",
"Through the Desert",
"Thurn and Taxis",
"Ticket to Ride",
"Tigris and Euphrates",
"Tikal",
"Timberland",
"Time's Up!",
"Top Secret Spies",
"Torres",
"Totopoly",
"Tracks to Telluride",
"TransAmerica",
"Travel Go",
"Trivial Pursuit",
"Trouble",
"Twilight Imperium",
"Ubongo",
"Upwords",
"Vanished Planet",
"Vinci",
"Wingspan",
"Yahtzee",
"Yut",
"Zombies!!!",
// Economics strategy games
// Games involving scarce resources and strategy.
"Acquire",
"Battleship",
"Catan",
"Diplomacy",
"Hotel",
"Junta",
"Kolejka",
"København",
"Monopoly",
"Power Grid",
"Race for the Galaxy",
"Risk",
"Risk 2210 A.D.",
"Root",
"Sentinels of the Multiverse",
"Squatter",
"Ticket to Ride",
"Triopoly",
// Games of physical skill
// Coordination, finesse, or other physical skills are necessary. Also known as dexterity games.
"Blockhead!",
"Buckaroo!",
"Camp Granada",
"Carrom",
"Chapayev",
"Crokinole",
"Dart Wars",
"Gnip Gnop",
"Hungry Hungry Hippos",
"Jenga",
"Kerplunk",
"Krazy Maze",
"Operation",
"Perfection",
"Polarity",
"Subbuteo",
"Twister",
"Villa Paletti",
// Children's games
// The rules are easy to learn and the outcome is mostly or entirely due to chance.
"Candy Land",
"Catan Junior",
"Chicken Cha Cha Cha",
"Don't Break the Ice",
"Don't Wake Daddy",
"Forbidden Bridge",
"Hey Pa! There's a Goat on the Roof",
"Hi Ho! Cherry-O",
"Hungry Hungry Hippos",
"The Kids of Catan",
"Mouse Trap",
"Snakes and Ladders (Chutes and Ladders)",
"Space Hop",
// Cooperative games
// Cooperative games in which all players need to work together to win.
"Arkham Horror",
"Battlestar Galactica: The Board Game",
"Betrayal at House on the Hill",
"Castle Panic",
"Flash Point: Fire Rescue",
"Forbidden Island",
"Freedom: The Underground Railroad",
"Gloomhaven",
"Hanabi",
"Just One",
"Lord of the Rings",
"Pandemic",
"Sentinels of the Multiverse",
"Shadows over Camelot",
"Space Alert",
"Spirit Island",
"What Next?",
"XCOM",
// Word games
// These games are based on the construction of words to score points.
"25 Words or Less",
"Acronymble",
"Aksharit",
"Alfapet",
"Bananagrams",
"The Big Taboo",
"Boggle",
"Kings Cribbage",
"Mad Gab",
"Pictionary",
"Probe",
"Scrabble",
"Thiruthamizh",
"Trickster",
"Upwords",
"Words with Friends",
// Gaming systems
// These are sets that can be used to play multiple games.
"Flibbix",
"Hanafuda",
"Icehouse pieces",
"Stonehenge"
];