exports.games = [
  {
    id: '1',
    bgg_id: '1',
    title: '"Monopoly"',
    description: '"a great way to lose friends"',
    minplayers: '2',
    maxplayers: '4',
    minplaytime: '10',
    maxplaytime: '120',
    age_recommendation: '10',
    complexity: '4',
    year_published: '1950',
    more_inf: 'null'
  },
  {
    id: '2',
    bgg_id: '2',
    title: '"Settlers of Catan"',
    description: '"another great way to lose friends"',
    minplayers: '2',
    maxplayers: '4',
    minplaytime: '10',
    maxplaytime: '1000',
    age_recommendation: '10',
    complexity: '4',
    year_published: '1975',
    more_inf: 'null'
  },
  {
    id: '3',
    bgg_id: '3',
    title: '"Settlers of Catan: Knights Edition"',
    description: '"another great way to lose friends',
    minplayers: ' but with knights this time"',
    maxplayers: '2',
    minplaytime: '4',
    maxplaytime: '10',
    age_recommendation: '60',
    complexity: '10',
    year_published: '4',
    more_inf: '1980'
  },
  {
    id: '4',
    bgg_id: '4',
    title: '"Code Names"',
    description: '"yell at your friends"',
    minplayers: '2',
    maxplayers: '4',
    minplaytime: '10',
    maxplaytime: '120',
    age_recommendation: '10',
    complexity: '4',
    year_published: '2000',
    more_inf: 'null'
  },
  {
    id: '5',
    bgg_id: '5',
    title: '"Risk"',
    description: '"a great way to spend 10 hours of your life and lose friends"',
    minplayers: '2',
    maxplayers: '4',
    minplaytime: '1000',
    maxplaytime: '999999',
    age_recommendation: '16',
    complexity: '20',
    year_published: '1965',
    more_inf: 'null'
  },
  {
    id: '6',
    bgg_id: '342900',
    title: '"Earthborne Rangers"',
    description: '"Earthborne Rangers is a customizable',
    minplayers: ' co-operative card game set in the wilderness of the far future. You take on the role of a Ranger',
    maxplayers: " a protector of the mountain valley you call home: a vast wilderness transformed by monumental feats of science and technology devised to save the Earth from destruction long ago.&lt;br/&gt;&lt;br/&gt;You begin by building a deck that reflects your Ranger's interests",
    minplaytime: ' personal history',
    maxplaytime: ' and personality. Then',
    age_recommendation: ' as you explore the open world and your story takes shape',
    complexity: ' you augment your deck with improved equipment',
    year_published: ' refined skills',
    more_inf: ' and the memories of your journey.&lt;br/&gt;&lt;br/&gt;The story of Earthborne Rangers is presented as a branching narrative campaign consisting of a main storyline and a multitude of side stories. In it'
  },
  {
    id: '7',
    bgg_id: '388367',
    title: '"Innovation Ultimate"',
    description: '"Innovation Ultimate contains the base game and five expansions. With the introduction of age 11',
    minplayers: ' many of the cards in the base game and the expansions have been updated.&lt;br/&gt;&lt;br/&gt;"',
    maxplayers: '2',
    minplaytime: '5',
    maxplaytime: '30',
    age_recommendation: '60',
    complexity: '14',
    year_published: '3',
    more_inf: '2024'
  },
  {
    id: '8',
    bgg_id: '396790',
    title: '"Nucleum"',
    description: '"When Elsa von Fr&amp;uuml;hlingfeld presented her invention to King Frederik Augustus II of Saxony',
    minplayers: ' people thought it was trickery. She used the recently isolated element Uranium to heat up a jar of water and used the resulting steam to power an engine that kept the Uranium active via a process she called &amp;ldquo;atomization.&amp;rdquo; Her device',
    maxplayers: ' the Nucleum',
    minplaytime: ' ushered in a new era of energy and prosperity over the next decades. Saxony went from a minor regional power to the hub of European science and engineering. Now',
    maxplaytime: ' a generation later',
    age_recommendation: ' factories are still hungry for more power',
    complexity: ' demanding bigger and more Nucleums to be built',
    year_published: ' more Uranium imported from the nearby country of Bohemia',
    more_inf: ' and railways and power lines built across the country to carry the tamed power of the atoms to Saxony&amp;rsquo;s great cities. Inventors'
  },
  {
    id: '9',
    bgg_id: '383179',
    title: '"Age of Innovation"',
    description: '"Age of Innovation is a standalone game set in the world of Terra Mystica.&lt;br/&gt;&lt;br/&gt;Twelve factions',
    minplayers: ' each with unique characteristics',
    maxplayers: ' populate this world of varying terrains. Here you will compete to erect buildings and merge them into cities. Each game allows you to create new combinations of factions',
    minplaytime: ' homelands',
    maxplaytime: " and abilities so that each game isn't the same as another.&lt;br/&gt;&lt;br/&gt;You control one of these factions and will terraform the game map's terrain into your homelands where you can erect your buildings. Proximity to other factions may limit your expansion",
    age_recommendation: ' but it also gains you significant advantages in the game. This tension adds to the appeal of the Terra Mystica series.&lt;br/&gt;&lt;br/&gt;Upgrade your buildings to gain valuable resources such as tools',
    complexity: ' scholars',
    year_published: ' money',
    more_inf: ' and power. Build schools to advance in different sciences and collect books'
  },
  {
    id: '10',
    bgg_id: '379078',
    title: '"Expeditions"',
    description: '"The sequel to Scythe sends players on a new adventure into Siberia',
    minplayers: ' where a massive meteorite crashed near the Tunguska River',
    maxplayers: ' awakening ancient corruption. An expedition led by Dr. Tarkovsky ventures into the taiga to learn about the meteorite and its impact on the land. Itching for adventure',
    minplaytime: ' heroes from the war privately fund their own expeditions to Siberia',
    maxplaytime: ' hoping to find artifacts',
    age_recommendation: ' overcome challenges',
    complexity: ' and ultimately achieve glory.&lt;br/&gt;&lt;br/&gt;Expeditions is a competitive',
    year_published: ' card-driven',
    more_inf: ' engine-building game of exploration. Play cards to gain power'
  },
  {
    id: '11',
    bgg_id: '366013',
    title: '"Heat: Pedal to the Metal"',
    description: '"Based on simple and intuitive hand management',
    minplayers: " Heat: Pedal to the Metal puts players in the driver's seat of intense car races",
    maxplayers: ' jockeying for position to cross the finish line first',
    minplaytime: " while managing their car's speed if they don't want to overheat. Selecting the right upgrades for their car will help them hug the curves and keep their engine cool enough to maintain top speeds. Ultimately",
    maxplaytime: ' their driving skills will be the key to victory!&lt;br/&gt;&lt;br/&gt;Drivers can compete in a single race or use the &amp;quot;Championship System&amp;quot; to play a whole season in one game night',
    age_recommendation: ' customizing their car before each race to claim the top spot of the podium. They have to be careful as the weather',
    complexity: ' road conditions',
    year_published: ' and events will change every race to spice up their championship. Players can also enjoy a solo mode with the Legends Module or add automated drivers as additional opponents in multiplayer games.&lt;br/&gt;&lt;br/&gt;&amp;mdash;description from the publisher&lt;br/&gt;&lt;br/&gt;"',
    more_inf: '1'
  },
  {
    id: '12',
    bgg_id: '342942',
    title: '"Ark Nova"',
    description: '"In Ark Nova',
    minplayers: ' you will plan and design a modern',
    maxplayers: ' scientifically managed zoo. With the ultimate goal of owning the most successful zoological establishment',
    minplaytime: ' you will build enclosures',
    maxplaytime: ' accommodate animals',
    age_recommendation: ' and support conservation projects all over the world. Specialists and unique buildings will help you in achieving this goal.&lt;br/&gt;&lt;br/&gt;Each player has a set of five action cards to manage their gameplay',
    complexity: ' and the power of an action is determined by the slot the card currently occupies. The cards in question are:&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;    CARDS: Allows you to gain new zoo cards (animals',
    year_published: ' sponsors',
    more_inf: ' and conservation project cards).&lt;br/&gt;    BUILD: Allows you to build standard or special enclosures'
  },
  {
    id: '13',
    bgg_id: '365258',
    title: '"World Wonders"',
    description: `"Take on the role of the great leaders of the past to build your own Ancient City.&lt;br/&gt;&lt;br/&gt;Each player will use their Gold each round to build tiles that will increase their city's economy. A city that produces more food and generates commerce brings more population. Make your city grow!&lt;br/&gt;&lt;br/&gt;There are 5 types of buildings`,
    minplayers: ' and each of them provides a type of resource that will make your city evolve from a simple settlement to the largest city in the  world. If your buildings are completely enclosed from all sides',
    maxplayers: " you've created a very well-planned city block. This will earn you a lot of points.&lt;br/&gt;&lt;br/&gt;To place new buildings to your city",
    minplaytime: ' you will also need a lot of roads. Adjacency with roads will allow you to place buildings further away from the map. This will reach natural resources',
    maxplaytime: ' which in addition to other benefits',
    age_recommendation: ' bring victory points.&lt;br/&gt;&lt;br/&gt;As important as the buildings',
    complexity: ' are its monuments and wonders tokens. This will bring you a lot of victory points',
    year_published: ' but will consume all your Gold. Be wise in choosing when and where to place it. Each monument requires buildings',
    more_inf: ' roads'
  },
  {
    id: '14',
    bgg_id: '363622',
    title: '"The Castles of Burgundy: Special Edition"',
    description: '"Castles of Burgundy is a legendary Board Game design created by Stefan Feld. In this 1-4 players tabletop experience',
    minplayers: ' you will take on the role of an aristocrat controlling a small princedom. Trying to build a settlement with powerful castles',
    maxplayers: ' practice trades',
    minplaytime: ' exploit silver mines',
    maxplaytime: ' and use the knowledge of travelers.&lt;br/&gt;Now',
    age_recommendation: ' this timeless game is coming back with an extremely polished',
    complexity: ' high-end special edition resulting from a collaboration between Ravensburger and Awaken Realms.&lt;br/&gt;&lt;br/&gt;In this special edition',
    year_published: ' you can expect a complete re-design of art and layout to ensure that every piece will have great art and enhance in-game usability. Only the best materials (cardboard',
    more_inf: ' cart paper'
  },
  {
    id: '15',
    bgg_id: '224517',
    title: '"Brass: Birmingham"',
    description: `"Brass: Birmingham is an economic strategy game sequel to Martin Wallace' 2007 masterpiece`,
    minplayers: ' Brass. Brass: Birmingham tells the story of competing entrepreneurs in Birmingham during the industrial revolution',
    maxplayers: ' between the years of 1770-1870.&lt;br/&gt;&lt;br/&gt;As in its predecessor',
    minplaytime: ' you must develop',
    maxplaytime: ' build',
    age_recommendation: ' and establish your industries and network',
    complexity: ' in an effort to exploit low or high market demands.&lt;br/&gt;&lt;br/&gt;Each round',
    year_published: ' players take turns according to the turn order track',
    more_inf: ' receiving two actions to perform any of the following actions (found in the original game):&lt;br/&gt;&lt;br/&gt;1) Build - Pay required resources and place an industry tile.&lt;br/&gt;2) Network - Add a rail / canal link'
  },
  {
    id: '16',
    bgg_id: '316554',
    title: '"Dune: Imperium"',
    description: '"Some important links: The Official FAQ',
    minplayers: ' the Unofficial FAQ',
    maxplayers: ' and an Automa (solo and 2p) Overview&lt;br/&gt;&lt;br/&gt;Dune: Imperium is a game that finds inspiration in elements and characters from the Dune legacy',
    minplaytime: ' both the new film from Legendary Pictures and the seminal literary series from Frank Herbert',
    maxplaytime: ' Brian Herbert',
    age_recommendation: ' and Kevin J. Anderson.&lt;br/&gt;&lt;br/&gt;As a leader of one of the Great Houses of the Landsraad',
    complexity: ' raise your banner and marshal your forces and spies. War is coming',
    year_published: ' and at the center of the conflict is Arrakis &amp;ndash; Dune',
    more_inf: ' the desert planet.&lt;br/&gt;&lt;br/&gt;Dune: Imperium uses deck-building to add a hidden-information angle to traditional worker placement.&lt;br/&gt;&lt;br/&gt;You start with a unique leader card'
  },
  {
    id: '17',
    bgg_id: '331106',
    title: '"The Witcher: Old World"',
    description: '"In The Witcher: Old World',
    minplayers: ' you become a witcher &amp;mdash; a professional monster slayer &amp;mdash; and immerse yourself in the legendary universe of The Witcher franchise.&lt;br/&gt;&lt;br/&gt;Set years before the saga of Geralt of Rivia',
    maxplayers: ' The Witcher: Old World explores a time when monsters roamed the Continent in greater numbers',
    minplaytime: ' creating a constant peril that required the attention of expertly trained monster slayers',
    maxplaytime: ' known as witchers. Five competing schools trained their adepts through brutal regimes',
    age_recommendation: ' and once fully prepared',
    complexity: ' these now-recognized witchers set off to explore the land',
    year_published: ' seeking trouble and adventures and helping others for coin.&lt;br/&gt;&lt;br/&gt;In this competitive adventure board game',
    more_inf: ' 2-5 players travel across a vast map'
  },
  {
    id: '18',
    bgg_id: '162886',
    title: '"Spirit Island"',
    description: '"In the most distant reaches of the world',
    minplayers: ' magic still exists',
    maxplayers: ' embodied by spirits of the land',
    minplaytime: ' of the sky',
    maxplaytime: ' and of every natural thing. As the great powers of Europe stretch their colonial empires further and further',
    age_recommendation: ' they will inevitably lay claim to a place where spirits still hold power - and when they do',
    complexity: ' the land itself will fight back alongside the islanders who live there.&lt;br/&gt;&lt;br/&gt;Spirit Island is a complex and thematic cooperative game about defending your island home from colonizing Invaders. Players are different spirits of the land',
    year_published: ' each with its own unique elemental powers. Every turn',
    more_inf: ' players simultaneously choose which of their power cards to play'
  },
  {
    id: '19',
    bgg_id: '350184',
    title: '"Earth"',
    description: '"Earth',
    minplayers: ' the soil that supports and sustains our beautiful planet',
    maxplayers: ' Earth. Over thousands of years of evolution and adaptation the flora and fauna of this unique planet have grown and developed into amazing life forms',
    minplaytime: ' creating symbiotic ecosystems and habitats.&lt;br/&gt;&lt;br/&gt;It&amp;rsquo;s time to jump into these rich environments and create some amazing natural synergies that replicate and extrapolate on Earth&amp;rsquo;s amazing versatility and plethora of natural resources. Create a self-supporting engine of growth',
    maxplaytime: ' expansion and supply where even your unused plants become compost for future growth.&lt;br/&gt;&lt;br/&gt;Earth is an open world engine builder for 1 to 5 players with simple rules but tons of strategic possibilities. With its encyclopedic nature and the enormous number of unique cards and combinations',
    age_recommendation: ' every single game will allow you to discover new synergies and connections',
    complexity: ' just as our vast and fascinating world allows us to do!&lt;br/&gt;&lt;br/&gt;&amp;mdash;description from the publisher&lt;br/&gt;&lt;br/&gt;"',
    year_published: '1',
    more_inf: '5'
  },
  {
    id: '20',
    bgg_id: '183685',
    title: '"Mr. President: The American Presidency',
    description: ' 2001-2020"',
    minplayers: `"Mr. President is a solitaire game about governing as the President of the United States. It's not an election game. It begins after you've been elected. It's about sitting in The Chair and trying to advance your agenda while navigating ongoing crises`,
    maxplayers: ' political enemies',
    minplaytime: ' public opinion',
    maxplaytime: ' your relations with Congress and the press',
    age_recommendation: ' and keeping your country secure in a world of rival nations and agendas that just seems to keep blowing up around you. Mr. President is a resource management game',
    complexity: ' where you never have enough resources to achieve your entire agenda',
    year_published: ' and the path you take through an always unpredictable storyline rests on the choices you make. Depending on the results of those choices',
    more_inf: ' and on the unfolding of a &amp;quot;different every game&amp;quot; story'
  },
  {
    id: '21',
    bgg_id: '243696',
    title: '"Race to the New Found Land"',
    description: '"Daring sailors explore the oceans and make a gigantic discovery: Newfoundland. The newly found land. A huge island off the coast of North America &amp;mdash; and right away a competition among nations breaks out. As so often happens',
    minplayers: ' everyone wants the biggest piece of land. In Race to the New Found Land',
    maxplayers: ' you must skillfully use your fleet to consistently present achievements to your royal house. Are you quick to set sail and populate the first known lands? Do you first explore new areas? Or do you trade and build your fleet first? Find out in this exciting race to Newfoundland!&lt;br/&gt;&lt;br/&gt;"',
    minplaytime: '2',
    maxplaytime: '4',
    age_recommendation: '60',
    complexity: '90',
    year_published: '10',
    more_inf: '2.7727'
  },
  {
    id: '22',
    bgg_id: '295770',
    title: '"Frosthaven"',
    description: '"Frosthaven is the story of a small outpost far to the north of the capital city of White Oak',
    minplayers: ' an outpost barely surviving the harsh weather as well as invasions from forces both known and unknown. There',
    maxplayers: ' a group of mercenaries at the end of their rope will help bring back this settlement from the edge of destruction. Not only will they have to deal with the harsh elements',
    minplaytime: ' but there are other',
    maxplaytime: ' far more dangerous threats out in the unforgiving cold as well. There are Algox',
    age_recommendation: ' the bigger',
    complexity: ' more yeti-like cousins of the Inox',
    year_published: ' attacking from the mountains; Lurkers flooding in from the northern sea; and rumors of machines that wander the frozen wastes of their own free will. The party of mercenaries must face all of these perils',
    more_inf: ' and perhaps in doing so'
  },
  {
    id: '23',
    bgg_id: '321608',
    title: '"Hegemony: Lead Your Class to Victory"',
    description: '"Extended edition includes Crisis &amp;amp; Control expansion.&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;The Nation is in disarray and a war is waging between the classes. The working class faces a dismantled welfare system',
    minplayers: ' the capitalists are losing their hard-earned profits',
    maxplayers: ' the middle class is gradually fading and the state is sinking into a deep deficit. Amidst all this chaos',
    minplaytime: ' the only person who can provide guidance is... you. Will you take the side of the working class and fight for social reforms? Or will you stand with the corporations and the free market? Will you help the government try to keep it all together',
    maxplaytime: ' or will you try to enforce your agenda no matter the cost to the country?&lt;br/&gt;&lt;br/&gt;Hegemony is an asymmetric politico-economic card-driven board game for 2-4 players that puts you in the role of one of the socio-economic groups in a fictional state: The Working Class',
    age_recommendation: ' the Middle Class',
    complexity: " the Capitalist Class and the State itself.&lt;br/&gt;&lt;br/&gt;The Working class controls the workers. The Capitalist class controls the companies. The Middle class combines elements from both the Working class and the Capitalist. It has workers who can work in the Capitalist's companies but it can also build companies of its own",
    year_published: ' yet smaller. Finally the State is trying to keep everyone happy',
    more_inf: ' providing benefits and subsidies when needed but trying also to maintain a steady income through taxes to avoid going into debt.&lt;br/&gt;&lt;br/&gt;While players have their own separate goals'
  },
  {
    id: '24',
    bgg_id: '266192',
    title: '"Wingspan"',
    description: '"Wingspan is&amp;nbsp;a competitive',
    minplayers: ' medium-weight',
    maxplayers: ' card-driven',
    minplaytime: " engine-building board game from Stonemaier Games. It's designed by Elizabeth Hargrave and features over 170 birds illustrated by Beth Sobel",
    maxplaytime: ' Natalia Rojas',
    age_recommendation: ' and Ana Maria Martinez.&lt;br/&gt;&lt;br/&gt;You are bird enthusiasts&amp;mdash;researchers',
    complexity: ' bird watchers',
    year_published: ' ornithologists',
    more_inf: ' and collectors&amp;mdash;seeking to discover and attract the best birds to your network of wildlife preserves. Each bird extends a chain of powerful combinations in one of your habitats (actions). These habitats  focus on several key aspects of growth:&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;     Gain food tokens via custom dice in a birdfeeder dice tower&lt;br/&gt;     Lay eggs using egg miniatures in a variety of colors&lt;br/&gt;     Draw from hundreds of unique bird cards and play them&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;The winner is the player with the most points after 4 rounds.&lt;br/&gt;&lt;br/&gt;&amp;mdash;description from the publisher&lt;br/&gt;&lt;br/&gt;From the 7th printing on'
  },
  {
    id: '25',
    bgg_id: '263895',
    title: '"City of the Great Machine"',
    description: '"City of the Great Machine is a strategy game set in a grim universe of technocratic Victorian steampunk. The game features the conflict between the Great Machine',
    minplayers: ' an artificial intelligence network',
    maxplayers: ' and an alliance of Heroes. The Great Machine is either controlled by a player or is automated',
    minplaytime: ' which completely changes the gameplay.&lt;br/&gt;&lt;br/&gt;The Great Machine controls the City built on mobile platforms in the sky. As the Great Machine',
    maxplaytime: " the player (or game AI) commands a force of perfected Servants and mechanical Guards. The Great Machine's ultimate goal is to suppress social unrest and complete its grandiose Master Plan to perfect the mankind.&lt;br/&gt;&lt;br/&gt;The other players are Heroes working together against the Great Machine to start a revolution. They encourage discontent in the City",
    age_recommendation: ' enlist the support of famous citizens',
    complexity: ' and inflame riots. They also attempt to prevent the Great Machine from completing the Master Plan',
    year_published: ' as it leads to the enslavement of the mankind.&lt;br/&gt;&lt;br/&gt;Game features:&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;     City of the Great Machine may be played as One-vs-Many (2-4 players) or cooperatively/solo (1-3 players).&lt;br/&gt;     Modular board allows for infinite City layouts. The players may reposition the City Districts during the game.&lt;br/&gt;     Hidden movement. Each round',
    more_inf: ' the Heroes secretly choose the Districts they will go to.&lt;br/&gt;     Resource management. Both sides of the conflict have multiple actions to take and pay for them in Trust (Heroes) or Bonds (the Great Machine). The same is true for movement and other tasks.&lt;br/&gt;     Asymmetric gameplay and unique victory conditions. The Heroes need 3 Riots to win'
  },
  {
    id: '26',
    bgg_id: '380619',
    title: '"Cyclades: Legendary Edition"',
    description: '"In the Cyclades archipelago',
    minplayers: ' off the shores of a divided Greece',
    maxplayers: ' players develop their cities and compete for supremacy under the watchful gaze of the gods.&lt;br/&gt;&lt;br/&gt;In Cyclades: Legendary Edition',
    minplaytime: ' designers Bruno Cathala and Ludovic Maublanc have reworked the Cyclades base game and its many expansions to make gameplay more dynamic and fluid.&lt;br/&gt;&lt;br/&gt;The game features a strategic bidding system that defines the actions available to each player on their turn. You must balance your finances to optimize the various actions provided by the different gods',
    maxplaytime: ' with each player gaining the support of only one god each turn. The game features a shorter and more dynamic bidding phase than the original Cyclades thanks to a new exponential bidding scale. Six gods are available instead of the five',
    age_recommendation: ' increasing the variety of actions available:&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;     Ares allows the movement of player armies and the building of fortresses.&lt;br/&gt;     Poseidon allows players to move their navies and build ports.&lt;br/&gt;     Zeus allows his followers to hire priests and build temples.&lt;br/&gt;     Athena provides her worshipers with philosophers and universities.&lt;br/&gt;     Apollo increases the income of his worshipers.&lt;br/&gt;     Hera provides mercenaries to enforce your troops during battle.&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;Players now use landscape tiles to assemble the modular game board during set-up',
    complexity: ' allowing for ever-changing maps and game strategies. New creatures and heroes are available in the base game',
    year_published: ' offering new strategic opportunities to build metropolises and gain decisive advantages on the battlefield. Your goal is to be the first to control three metropolises',
    more_inf: ' which can be obtained as follows:&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;     Economic development'
  },
  {
    id: '27',
    bgg_id: '394186',
    title: '"Ports: A Game of Battles with Boats"',
    description: '"Ports is a game about abstracted trade between two city-states along a life-giving river. The genesis of the game was as a chess mini-game in an RPG',
    minplayers: ' but it quickly became more interesting than its container. It plays similar to traditional race games such as Backgammon',
    maxplayers: ' Sennet',
    minplaytime: ' and the Royal Game of Ur',
    maxplaytime: ' with its canonical theme being trade and privateers competing on a Nile-type river.&lt;br/&gt;&lt;br/&gt;On a fish-shaped board',
    age_recommendation: ' there are two ports on one side and a winding river that overlaps itself that connects the two. Each player starts with three merchant ships in their port and there are two reinforcements for each player on the island in the middle of the river. Each player rolls four binary dice in order to move their ships along the river',
    complexity: " ultimately to the other player's port. If one player's boat lands the other's boat",
    year_published: ` then they roll to see who wins the battle and whose boat needs to retreat to their original port. Whoever gets three boats to their opponent's port first wins!&lt;br/&gt;&lt;br/&gt;&amp;mdash;description from the designer&lt;br/&gt;&lt;br/&gt;"`,
    more_inf: '2'
  },
  {
    id: '28',
    bgg_id: '167791',
    title: '"Terraforming Mars"',
    description: '"In the 2400s',
    minplayers: ' mankind begins to terraform the planet Mars. Giant corporations',
    maxplayers: ' sponsored by the World Government on Earth',
    minplaytime: ' initiate huge projects to raise the temperature',
    maxplaytime: ' the oxygen level',
    age_recommendation: ' and the ocean coverage until the environment is habitable. In Terraforming Mars',
    complexity: ' you play one of those corporations and work together in the terraforming process',
    year_published: ' but compete for getting victory points that are awarded not only for your contribution to the terraforming',
    more_inf: ' but also for advancing human infrastructure throughout the solar system'
  },
  {
    id: '29',
    bgg_id: '312484',
    title: '"Lost Ruins of Arnak"',
    description: '"On an uninhabited island in uncharted seas',
    minplayers: ' explorers have found traces of a great civilization. Now you will lead an expedition to explore the island',
    maxplayers: ' find lost artifacts',
    minplaytime: ' and face fearsome guardians',
    maxplaytime: " all in a quest to learn the island's secrets.&lt;br/&gt;&lt;br/&gt;Lost Ruins of Arnak combines deck-building and worker placement in a game of exploration",
    age_recommendation: ' resource management',
    complexity: ' and discovery. In addition to traditional deck-builder effects',
    year_published: ' cards can also be used to place workers',
    more_inf: ' and new worker actions become available as players explore the island. Some of these actions require resources instead of workers'
  },
  {
    id: '30',
    bgg_id: '295947',
    title: '"Cascadia"',
    description: '"Cascadia is a puzzly tile-laying and token-drafting game featuring the habitats and wildlife of the Pacific Northwest.&lt;br/&gt;&lt;br/&gt;In the game',
    minplayers: ' you take turns building out your own terrain area and populating it with wildlife. You start with three hexagonal habitat tiles (with the five types of habitat in the game)',
    maxplayers: " and on a turn you choose a new habitat tile that's paired with a wildlife token",
    minplaytime: ' then place that tile next to your other ones and place the wildlife token on an appropriate habitat. (Each tile depicts 1-3 types of wildlife from the five types in the game',
    maxplaytime: ' and you can place at most one tile on a habitat.) Four tiles are on display',
    age_recommendation: ' with each tile being paired at random with a wildlife token',
    complexity: " so you must make the best of what's available &amp;mdash; unless you have a nature token to spend so that you can pick your choice of each item.&lt;br/&gt;&lt;br/&gt;Ideally you can place habitat tiles to create matching terrain that reduces fragmentation and creates wildlife corridors",
    year_published: " mostly because you score for the largest area of each type of habitat at game's end",
    more_inf: " with a bonus if your group is larger than each other player's. At the same time"
  },
  {
    id: '31',
    bgg_id: '237182',
    title: '"Root"',
    description: `"Root is a game of adventure and war in which 2 to 4 (1 to 6 with the 'Riverfolk' expansion) players battle for control of a vast wilderness.&lt;br/&gt;&lt;br/&gt;The nefarious Marquise de Cat has seized the great woodland`,
    minplayers: ' intent on harvesting its riches. Under her rule',
    maxplayers: ' the many creatures of the forest have banded together. This Alliance will seek to strengthen its resources and subvert the rule of Cats. In this effort',
    minplaytime: ' the Alliance may enlist the help of the wandering Vagabonds who are able to move through the more dangerous woodland paths. Though some may sympathize with the Alliance&amp;rsquo;s hopes and dreams',
    maxplaytime: ' these wanderers are old enough to remember the great birds of prey who once controlled the woods.&lt;br/&gt;&lt;br/&gt;Meanwhile',
    age_recommendation: ' at the edge of the region',
    complexity: ' the proud',
    year_published: ' squabbling Eyrie have found a new commander who they hope will lead their faction to resume their ancient birthright. The stage is set for a contest that will decide the fate of the great woodland. It is up to the players to decide which group will ultimately take root.&lt;br/&gt;&lt;br/&gt;Root represents the next step in our development of asymmetric design. Like Vast: The Crystal Caverns',
    more_inf: ' each player in Root has unique capabilities and a different victory condition. Now'
  },
  {
    id: '32',
    bgg_id: '396618',
    title: '"Waterfall Park"',
    description: '"Welcome to Waterfall Park',
    minplayers: ' a revamped edition of Chinatown',
    maxplayers: ' the well-known negotiation game. The goal of the game is to trade and exchange attractions to build the biggest amusement park in the world. The particularity of this park is that it is built vertically on huge towers in the middle of the ocean.&lt;br/&gt;&lt;br/&gt;Waterfall Park is shorter and more family friendly than Chinatown',
    minplaytime: ' and the exchanges and interactions have been significantly increased to make the game even better.&lt;br/&gt;&lt;br/&gt;&amp;mdash;description from the publisher&lt;br/&gt;&lt;br/&gt;"',
    maxplaytime: '3',
    age_recommendation: '5',
    complexity: '45',
    year_published: '45',
    more_inf: '10'
  },
  {
    id: '33',
    bgg_id: '199792',
    title: '"Everdell"',
    description: '"Within the charming valley of Everdell',
    minplayers: ' beneath the boughs of towering trees',
    maxplayers: ' among meandering streams and mossy hollows',
    minplaytime: ' a civilization of forest critters is thriving and expanding. From Everfrost to Bellsong',
    maxplaytime: ' many a year have come and gone',
    age_recommendation: ' but the time has come for new territories to be settled and new cities established. You will be the leader of a group of critters intent on just such a task. There are buildings to construct',
    complexity: ' lively characters to meet',
    year_published: ' events to host&amp;mdash;you have a busy year ahead of yourself. Will the sun shine brightest on your city before the winter moon rises?&lt;br/&gt;&lt;br/&gt;Everdell is a game of dynamic tableau building and worker placement.&lt;br/&gt;&lt;br/&gt;On their turn a player can take one of three actions:&lt;br/&gt;&lt;br/&gt;a) Place a Worker: Each player has a collection of Worker pieces. These are placed on the board locations',
    more_inf: ' events'
  },
  {
    id: '34',
    bgg_id: '205637',
    title: '"Arkham Horror: The Card Game"',
    description: '"Something evil stirs in Arkham',
    minplayers: ' and only you can stop it. Blurring the traditional lines between role-playing and card game experiences',
    maxplayers: ' Arkham Horror: The Card Game is a Living Card Game of Lovecraftian mystery',
    minplaytime: ' monsters',
    maxplaytime: ' and madness!&lt;br/&gt;&lt;br/&gt;In the game',
    age_recommendation: ' you and your friend (or up to three friends with two Core Sets) become characters within the quiet New England town of Arkham. You have your talents',
    complexity: ' sure',
    year_published: " but you also have your flaws. Perhaps you've dabbled a little too much in the writings of the Necronomicon",
    more_inf: ' and its words continue to haunt you. Perhaps you feel compelled to cover up any signs of otherworldly evils'
  },
  {
    id: '35',
    bgg_id: '332772',
    title: '"Revive"',
    description: '"Revive civilization',
    minplayers: " 5000 years after everything was destroyed. Lead your tribe and explore the frozen earth. Harness its resources. Recruit surface survivors to your cause. Build factories with powerful machines. And populate ancient sites to relearn your tribe's forgotten technologies.&lt;br/&gt;--&lt;br/&gt;Revive is a game for 1-4 players with asymmetric player powers",
    maxplayers: ' highly variable setup',
    minplaytime: ' and no fighting or direct conflict. Playing through the 5-part campaign unlocks additional contents',
    maxplaytime: ' and once all contents have been unlocked',
    age_recommendation: ' the game can be replayed indefinitely.&lt;br/&gt;--&lt;br/&gt;At the beginning of the game',
    complexity: ' each player gets a set of citizen cards',
    year_published: ' a tribe board',
    more_inf: ' as well as a huge dual-layer player board. The tribe board shows your unique tribe ability and the ancient technologies that you may relearn during the game. The dual-layer player board is where you place your custom machines and upgrade your card slots.&lt;br/&gt;&lt;br/&gt;A main goal of the game is to reach and populate the large ancient sites. These ancient locations are randomized'
  },
  {
    id: '36',
    bgg_id: '394897',
    title: '"Horror on the Orient Express: The Board Game"',
    description: '"Horror on the Orient Express: The Board Game lures you into the luxurious',
    minplayers: ' yet dangerous interiors of the most famous train of the 1920s. The magnificent engine travels into the realm of the Dreamlands &amp;mdash; with you on board! From hideous monsters crawling out of breaches to cultists hiding among the decadent passengers',
    maxplayers: ' everything is against you',
    minplaytime: ' not forgetting an eldritch',
    maxplaytime: ' blood-thirsty vampire hunting down everything that moves...all against the clock. Can you beat them all as you investigate the dark secrets of the Orient Express?&lt;br/&gt;&lt;br/&gt;In the game',
    age_recommendation: ' you control a character who can develop new skills',
    complexity: ' gather items',
    year_published: ' talk to the passengers',
    more_inf: ' discover clues and'
  },
  {
    id: '37',
    bgg_id: '359156',
    title: '"Darwin&#039;s Journey"',
    description: '"Welcome to Darwin Awards party card game! Do you enjoy reading or hearing about the crazy things that people do that sometimes end up with them being amongst the nonliving&amp;hellip;in other words',
    minplayers: ' someone doing something really stupid and dying. Do you like to make fun of your family',
    maxplayers: ' friends',
    minplaytime: ' perfect strangers',
    maxplaytime: ' or maybe a celebrity? Then Darwin Awards party card game is for you!&lt;br/&gt;&lt;br/&gt;Darwin Awards is comprised of 4 different decks of cards; there are Location',
    age_recommendation: ' Action',
    complexity: ' Object',
    year_published: ' and Death cards. For advanced gameplay',
    more_inf: ' you can add a 5th deck'
  },
  {
    id: '38',
    bgg_id: '169786',
    title: '"Scythe"',
    description: '"It is a time of unrest in 1920s Europa. The ashes from the first great war still darken the snow. The capitalistic city-state known simply as &amp;ldquo;The Factory&amp;rdquo;',
    minplayers: ' which fueled the war with heavily armored mechs',
    maxplayers: ' has closed its doors',
    minplaytime: ' drawing the attention of several nearby countries.&lt;br/&gt;&lt;br/&gt;Scythe is an engine-building game set in an alternate-history 1920s period. It is a time of farming and war',
    maxplaytime: ' broken hearts and rusted gears',
    age_recommendation: ' innovation and valor. In Scythe',
    complexity: " each player represents a character from one of five factions of Eastern Europe who are attempting to earn their fortune and claim their faction's stake in the land around the mysterious Factory. Players conquer territory",
    year_published: ' enlist new recruits',
    more_inf: ' reap resources'
  },
  {
    id: '39',
    bgg_id: '363369',
    title: '"Starship Captains"',
    description: '"Welcome aboard and congrats on the promotion! Your &amp;quot;new&amp;quot; starship is ready to embark on its first big voyage. Just scrape off some of the rust',
    minplayers: " and she'll do fine. And that crew? Might look a little green around the edges",
    maxplayers: " but they're your crew now. Make us proud.&lt;br/&gt;&lt;br/&gt;The stars are calling...and adventure awaits!&lt;br/&gt;&lt;br/&gt;As newly promoted Starship Captains",
    minplaytime: ' players are in command of their first starship and hungry to prove themselves in a galaxy full of space pirates',
    maxplaytime: ' grumpy old androids',
    age_recommendation: ' ancient artifacts',
    complexity: ' and interplanetary adventures.&lt;br/&gt;&lt;br/&gt;In this 1-4 player Eurostyle game',
    year_published: ' which mixes action selection and engine building',
    more_inf: " you'll manage a diverse crew of cadets"
  },
  {
    id: '40',
    bgg_id: '174430',
    title: '"Gloomhaven"',
    description: '"Gloomhaven  is a game of Euro-inspired tactical combat in a persistent world of shifting motives. Players will take on the role of a wandering adventurer with their own special set of skills and their own reasons for traveling to this dark corner of the world. Players must work together out of necessity to clear out menacing dungeons and forgotten ruins. In the process',
    minplayers: ' they will enhance their abilities with experience and loot',
    maxplayers: ' discover new locations to explore and plunder',
    minplaytime: ' and expand an ever-branching story fueled by the decisions they make.&lt;br/&gt;&lt;br/&gt;This is a game with a persistent and changing world that is ideally played over many game sessions. After a scenario',
    maxplaytime: ' players will make decisions on what to do',
    age_recommendation: ' which will determine how the story continues',
    complexity: ' kind of like a &amp;ldquo;Choose Your Own Adventure&amp;rdquo; book. Playing through a scenario is a cooperative affair where players will fight against automated monsters using an innovative card system to determine the order of play and what a player does on their turn.&lt;br/&gt;&lt;br/&gt;Each turn',
    year_published: ' a player chooses two cards to play out of their hand. The number on the top card determines their initiative for the round. Each card also has a top and bottom power',
    more_inf: ' and when it is a player&amp;rsquo;s turn in the initiative order'
  },
  {
    id: '41',
    bgg_id: '371947',
    title: '"3 Ring Circus"',
    description: '"The circus has come to town! Under the tent',
    minplayers: ' jugglers',
    maxplayers: ' clowns',
    minplaytime: ' magicians',
    maxplaytime: ' strongmen and wild beasts capture the curiosity of a dedicated audience that applauds non-stop. After each performance',
    age_recommendation: ' your little troupe accumulates fame and may one day pique the interest of P.T. Barnum',
    complexity: ' the greatest circus mogul of all time.&lt;br/&gt;&lt;br/&gt;In 3 Ring Circus',
    year_published: ' players take on the role of a circus director who tours the United States at the end of the 19th century. Your objective is to hire artists and offer performances in various towns and cities with the intention of gaining fame. In towns',
    more_inf: ' features are easy to set up and give you starting resources to upgrade your cast; small cities are somewhat more demanding'
  },
  {
    id: '42',
    bgg_id: '285774',
    title: '"Marvel Champions: The Card Game"',
    description: '"&amp;quot;With great power',
    minplayers: ' there must also come great responsibility.&amp;quot;&lt;br/&gt;   &amp;ndash;Stan Lee',
    maxplayers: ' Amazing Fantasy #15&lt;br/&gt;&lt;br/&gt;Iron Man and Black Panther team up to stop Rhino from rampaging through the streets of New York. Captain Marvel and Spider-Man battle Ultron as he threatens global annihilation. Do you have what it takes to join the ranks of these legendary heroes and become a champion?&lt;br/&gt;&lt;br/&gt;Jump into the Marvel Universe with Marvel Champions: The Card Game',
    minplaytime: ' a cooperative Living Card Game for one to four players!&lt;br/&gt;&lt;br/&gt;Marvel Champions: The Card Game invites players to embody iconic heroes from the Marvel Universe as they battle to stop infamous villains from enacting their devious schemes. As a Living Card Game',
    maxplaytime: ' Marvel Champions is supported with regular releases of new product',
    age_recommendation: ' including new heroes and scenarios.&lt;br/&gt;&lt;br/&gt;&amp;mdash;description from the publisher&lt;br/&gt;&lt;br/&gt;"',
    complexity: '1',
    year_published: '4',
    more_inf: '45'
  },
  {
    id: '43',
    bgg_id: '271320',
    title: '"The Castles of Burgundy"',
    description: '"The Castles of Burgundy is set in the Burgundy region of High Medieval France. Each player takes on the role of an aristocrat',
    minplayers: ' originally controlling a small princedom. While playing',
    maxplayers: ' they aim to build settlements and powerful castles',
    minplaytime: ' practice trade along the river',
    maxplaytime: ' exploit silver mines',
    age_recommendation: ' and use the knowledge of travelers.&lt;br/&gt;&lt;br/&gt;The game is about players taking settlement tiles from the game board and placing them into their princedom',
    complexity: ' which is represented by the player board. Every tile has a function that starts when the tile is placed in the princedom. The princedom itself consists of several regions',
    year_published: ' each of which demands its own type of settlement tile.&lt;br/&gt;&lt;br/&gt;The game is played in five phases',
    more_inf: ' each consisting of five rounds. Each phase begins with the game board stocked with settlement tiles and goods tiles. At the beginning of each round'
  },
  {
    id: '44',
    bgg_id: '63888',
    title: '"Innovation"',
    description: '"This game by Carl Chudyk is a journey through innovations from the stone age through modern times.  Each player builds a civilization based on various technologies',
    minplayers: ' ideas',
    maxplayers: ' and cultural advancements',
    minplaytime: ' all represented by cards.  Each of these cards has a unique power which will allow further advancement',
    maxplaytime: ' point scoring',
    age_recommendation: ' or even attacking other civilizations.  Be careful though',
    complexity: ' as other civilizations may be able to benefit from your ideas as well!&lt;br/&gt;&lt;br/&gt;To win',
    year_published: ' you must score achievements',
    more_inf: ' which you can attain by amassing points or by meeting certain criteria with the innovations you have built.  Plan your civilization well'
  },
  {
    id: '45',
    bgg_id: '177736',
    title: '"A Feast for Odin"',
    description: '"A Feast for Odin is a saga in the form of a board game. You are reliving the cultural achievements',
    minplayers: ' mercantile expeditions',
    maxplayers: ' and pillages of those tribes we know as Viking today &amp;mdash; a term that was used quite differently towards the end of the first millennium.&lt;br/&gt;&lt;br/&gt;When the northerners went out for a raid',
    minplaytime: ' they used to say they headed out for a viking. Their Scandinavian ancestors',
    maxplaytime: ' however',
    age_recommendation: ' were much more than just pirates. They were explorers and founders of states. Leif Eriksson is said to be the first European in America',
    complexity: ' long before Columbus.&lt;br/&gt;In what is known today as Normandy',
    year_published: ' the intruders were not called Vikings but Normans. One of them is the famous William the Conqueror who invaded England in 1066. He managed to do what the king of Norway failed to do only a few years prior: conquer the Throne of England. The reason why the people of these times became such strong seafarers is due to their unfortunate agricultural situation. Crop shortfalls caused great distress.&lt;br/&gt;&lt;br/&gt;In this game',
    more_inf: ' you will raid and explore new territories. You will also experience their day-to-day activities: collecting goods to achieve a financially secure position in society. In the end'
  },
  {
    id: '46',
    bgg_id: '37512',
    title: '"Federation"',
    description: '"A game of galactic conflict based on the Star Trek universe.&lt;br/&gt;&lt;br/&gt;The players control one of six powers: United Federation of Planets',
    minplayers: ' Klingon Empire',
    maxplayers: ' Romulan Star Empire',
    minplaytime: ' Ferengi Alliance',
    maxplaytime: ' Cardassian Union',
    age_recommendation: ' or Borg Collective. The object of the game is to control over 60% of the planetary systems on the map.&lt;br/&gt;&lt;br/&gt;Components include an area-movement space map',
    complexity: ' a deck of Action Cards tailored to the theme',
    year_published: ' and sets of unit counters.&lt;br/&gt;&lt;br/&gt;This game is a module for the Warp Empires system',
    more_inf: ' the core rules are required for play.&lt;br/&gt;&lt;br/&gt;"'
  },
  {
    id: '47',
    bgg_id: '12',
    title: '"Ra"',
    description: '"Ra is an auction and set-collection game with an Ancient Egyptian theme.  Each turn players are able to purchase lots of tiles with their bidding tiles (suns).  Once a player has used up his or her suns',
    minplayers: ' the other players continue until they do likewise',
    maxplayers: ' which may set up a situation with a single uncontested player bidding on tiles before the end of the round occurs.  Tension builds because the round may end before all players have had a chance to win their three lots for the epoch.  The various tiles either give immediate points',
    minplaytime: ' prevent negative points for not having certain types at the end of the round (epoch)',
    maxplaytime: ' or give points after the final round.  The game lasts for three &amp;quot;epochs&amp;quot; (rounds).  The game offers a short learning curve',
    age_recommendation: ' and experienced players find it both fast-moving and a quick play.&lt;br/&gt;&lt;br/&gt;From the Box:&lt;br/&gt;The game spans 1500 years of Egyptian history in less than an hour!&lt;br/&gt;The players seek to expand their power and fame and there are many ways to accomplish this: Influencing Pharaohs',
    complexity: ' Building monuments',
    year_published: ' Farming on the Nile',
    more_inf: ' Paying homage to the Gods'
  },
  {
    id: '48',
    bgg_id: '394334',
    title: '"Sunrise Lane"',
    description: '"In Sunrise Lane',
    minplayers: ' players take on the role of construction companies attempting to build up a residential neighborhood',
    maxplayers: ' and to do this',
    minplaytime: ' they need to pick prestigious plots of land on which to build houses and town structures.&lt;br/&gt;            &lt;br/&gt;In more detail',
    maxplaytime: ' the game board depicts a grid of spaces that each show 1-5 dots in a single color',
    age_recommendation: ' and each player has a set of colored House pieces',
    complexity: ' with the colors having no connection to the space on the board. On a turn',
    year_published: ' you either draw 2 colored cards from the deck and add them to your hand (with a limit of 5 cards in hand) or discard cards to place a building',
    more_inf: ' then draw a card.&lt;br/&gt;            &lt;br/&gt;When you build'
  },
  {
    id: '49',
    bgg_id: '258779',
    title: '"Planet Unknown"',
    description: '"Our planet has run out of resources',
    minplayers: ' and we are forced to move. We have discovered a series of planets and sent our rovers to test their environment with the hope of colonization. Our rovers have confirmed 1-6 viable colonization options.&lt;br/&gt;&lt;br/&gt;Planet Unknown is a competitive game for 1-6 players in which players attempt to develop the best planet. Each round',
    maxplayers: ' each player places one polyomino-shaped',
    minplaytime: " dual-resource tile on their planet. Each resource represents the infrastructure needed to support life on the planet. Every tile placement is important to cover your planet efficiently and also to build up your planet's engine. After placing the tile",
    maxplaytime: " players do two actions associated with the two infrastructure types on the tile. Some tile placements trigger &amp;quot;meteors&amp;quot; that make all planets harder to develop and prevent them from scoring points in the meteor's row and column.&lt;br/&gt;&lt;br/&gt;Planet Unknown innovates on the popular polyomino trend by allowing simultaneous",
    age_recommendation: ' yet strategic turn-based play via the Lazy S.U.S.A.N. space station in the center of the table.&lt;br/&gt;&lt;br/&gt;&amp;mdash;description from the publisher&lt;br/&gt;&lt;br/&gt;"',
    complexity: '1',
    year_published: '6',
    more_inf: '60'
  },
  {
    id: '50',
    bgg_id: '375209',
    title: '"Space Alone"',
    description: '"A roll&amp;amp;write game about survival on a on a foreign planet .&lt;br/&gt;&lt;br/&gt;The game is designed for 1 to 4 players',
    minplayers: ' age 12+ with an average game time is 20-40 minutes.&lt;br/&gt;&lt;br/&gt;In each turn',
    maxplayers: ' the active player rolls 4 D6 dice and performs actions using the dice pool. The goal of the game is to perform the scenario. For example: Carry out an exploratory mission',
    minplaytime: ' repair a ship',
    maxplaytime: ' contact a space station.&lt;br/&gt;&lt;br/&gt;The biggest obstacle during the game is declining oxygen levels',
    age_recommendation: ' radiation protection and generation of energy needed to use technology. It is also possible to die at the hands of another player and various dangers on the planet.In addition to taking care of his fate',
    complexity: ' the player also has his space vehicle',
    year_published: ' which is a separate location .This ship can be developed',
    more_inf: ' repaired and used in a number of ways specified in the scenario. It is a HUB to which the player regularly returns with the acquired resources.&lt;br/&gt;&lt;br/&gt;The game continues until the scenario is completed or all players die.&lt;br/&gt;&lt;br/&gt;&amp;mdash;description from the designer&lt;br/&gt;&lt;br/&gt;"'
  },
  {
    id: '51',
    bgg_id: '230802',
    title: '"Azul"',
    description: '"Introduced by the Moors',
    minplayers: ' azuleijos (originally white and blue ceramic tiles) were fully embraced by the Portuguese when their king Manuel I',
    maxplayers: ' on a visit to the Alhambra palace in Southern Spain',
    minplaytime: ' was mesmerized by the stunning beauty of the Moorish decorative tiles. The king',
    maxplaytime: ' awestruck by the interior beauty of the Alhambra',
    age_recommendation: ' immediately ordered that his own palace in Portugal be decorated with similar wall tiles. As a tile-laying artist',
    complexity: ' you have been challenged to embellish the walls of the Royal Palace of Evora.&lt;br/&gt;&lt;br/&gt;In the game Azul',
    year_published: ' players take turns drafting colored tiles from suppliers to their player board. Later in the round',
    more_inf: ` players score points based on how they've placed their tiles to decorate the palace. Extra points are scored for specific patterns and completing sets; wasted supplies harm the player's score. The player with the most points at the end of the game wins.&lt;br/&gt;&lt;br/&gt;"`
  },
  {
    id: '52',
    bgg_id: '275284',
    title: '"Arkeis"',
    description: '"History is full of secrets...&lt;br/&gt;&lt;br/&gt;As they explore an ancient Egyptian tomb',
    minplayers: ' a team of archaeologists and adventurers stumble upon a mystery that History forgot. To uncover the truth',
    maxplayers: ' they will have to delve deeper and deeper in the pyramids',
    minplaytime: ' dodging deadly traps and fighting back swathes of monsters running after them. Has the old Pharaoh placed a curse on this expedition? Should some secrets remain untold? This story is now yours to complete...&lt;br/&gt;&lt;br/&gt;Arkeis is a cooperative',
    maxplaytime: ' story-driven',
    age_recommendation: ' campaign game with minis set among ancient Egyptian ruins. &lt;br/&gt;Each player takes control of an adventurer as they explore a modular board.&lt;br/&gt;Players have up to two actions per turn: search',
    complexity: ' move',
    year_published: ' assist an ally or fight one of the numerous dangers waiting for them in the tombs! The results of their actions can be altered by the equipment and character upgrades they earn during the campaign. &lt;br/&gt; They can push their luck at the risk of being cursed or suffering lasting traumas from injuries!&lt;br/&gt;Each character has their own backpack to store their items (and curses) between adventures.&lt;br/&gt;Each scenario has objectives that the players will try to accomplish during the game to earn rewards in the form of key items and upgrades that influence later scenarios.&lt;br/&gt;&lt;br/&gt;It will take a team of skilled players to reveal all of Arkeis&amp;rsquo;s secrets!&lt;br/&gt;&lt;br/&gt;&amp;mdash;description from publisher&lt;br/&gt;&lt;br/&gt;"',
    more_inf: '1'
  },
  {
    id: '53',
    bgg_id: '251247',
    title: '"Barrage"',
    description: '"In the dystopic 1930s',
    minplayers: ' the industrial revolution pushed the exploitation of fossil-based resources to the limit',
    maxplayers: ' and now the only thing powerful enough to quench the thirst for power of the massive machines and of the unstoppable engineering progress is the unlimited hydroelectric energy provided by the rivers.&lt;br/&gt;&lt;br/&gt;Barrage is a resource management strategic game in which players compete to build their majestic dams',
    minplaytime: ' raise them to increase their storing capacity',
    maxplaytime: ' and deliver all the potential power through pressure tunnels connected to the energy turbines of their powerhouses.&lt;br/&gt;&lt;br/&gt;Each player represents one of the four international companies who are gathering machinery',
    age_recommendation: ' innovative patents and brilliant engineers to claim the best locations to collect and exploit the water of a contested Alpine region crossed by rivers.&lt;br/&gt;&lt;br/&gt;Barrage includes two innovative and challenging mechanisms. First',
    complexity: ' the players must carefully plan their actions and handle their machinery',
    year_published: ' since both their action tokens and resources are stored on a Construction Wheel and will only be available after a full turn of the wheel. The better you manage your wheel',
    more_inf: ' the earlier your resources and actions come back to you.&lt;br/&gt;&lt;br/&gt;Second'
  },
  {
    id: '54',
    bgg_id: '337627',
    title: '"Voidfall"',
    description: '"For centuries',
    minplayers: ' the Novarchs',
    maxplayers: ' descendants of the royal House of Novarchon',
    minplaytime: ' have ruled with an iron fist over the feudalistic galactic empire of humankind',
    maxplaytime: ' the Domineum. During this time',
    age_recommendation: ' they brought stunning technological innovation and scientific advancements to their domain. This accelerated progression helped the Domineum reach &amp;mdash; and eventually inhabit &amp;mdash; even the farthest segments of the known galaxy',
    complexity: ' where new Houses emerged to govern the outer sectors of the empire. As the House of Novarchon grew in power',
    year_published: ' so grew the religious cult that surrounded them',
    more_inf: ' proclaiming grim prophecies about an ancient cosmic being from another dimension: the Voidborn.&lt;br/&gt;&lt;br/&gt;Many thought it to be only a myth'
  },
  {
    id: '55',
    bgg_id: '3481',
    title: '"Nemesis"',
    description: '"A 3D starships miniatures game settled in deep space.&lt;br/&gt;&lt;br/&gt;"',
    minplayers: '2',
    maxplayers: '2',
    minplaytime: '30',
    maxplaytime: '30',
    age_recommendation: '8',
    complexity: '2',
    year_published: '1998',
    more_inf: '"https://boardgamegeek.com/boardgame/3481/nemesis"'
  },
  {
    id: '56',
    bgg_id: '146144',
    title: '"A.E.G.I.S.: Combining Robot Strategy Game"',
    description: `"Who doesn't love combining robots? A.E.G.I.S.: Combining Robot Strategy Game is the world&amp;rsquo;s best combining robot tabletop game! Using themes from all your favorite giant mecha shows`,
    minplayers: ' it takes elements from popular tabletop wargames and streamlines them to make a game with the same depth of strategy without the high learning curve',
    maxplayers: " distance measuring and long play times. Players build teams out of five robots to duke it out against other players' teams of five. It's designed to be easy to learn",
    minplaytime: ' affordable to buy',
    maxplaytime: ' and quick to play',
    age_recommendation: ' setting it apart from other strategy games.&lt;br/&gt;&lt;br/&gt;There are five different classes of robot: Assault',
    complexity: ' Evasive',
    year_published: ' Guard',
    more_inf: ' Intel and Support'
  },
  {
    id: '57',
    bgg_id: '306721',
    title: '"A.E.G.I.S.: Combining Robot Strategy Game – Ell Gel Ion Promo Card"',
    description: '"Originally available as part of the Promo Paradise 2019 Kickstarter campaign.&lt;br/&gt;&lt;br/&gt;Flight&lt;br/&gt;Retaliate&lt;br/&gt;Scrap Awakening: You may combine into this robot using any of your destroyed robots as components. Class and Make requirements still matter and at least one component must still be on the board&lt;br/&gt;&lt;br/&gt;Integrity 7&lt;br/&gt;&lt;br/&gt;"',
    minplayers: '2',
    maxplayers: '6',
    minplaytime: '20',
    maxplaytime: '120',
    age_recommendation: '10',
    complexity: '0',
    year_published: '2019',
    more_inf: '"https://boardgamegeek.com/boardgame/306721/a.e.g.i.s.: combining robot strategy game – ell gel ion promo card"'
  },
  {
    id: '58',
    bgg_id: '259420',
    title: '"A.E.G.I.S.: Combining Robot Strategy Game – Variant Command Expansion Set"',
    description: `"During the Five Nations War's greatest battles`,
    minplayers: ' the robots of these new heroes and villains took on powerful new forms when the situation was dire!&lt;br/&gt;&lt;br/&gt;Promo set of Variant Commander Robots for A.E.G.I.S. for use after the campaign mode',
    maxplayers: ' variants each have a combination of alternative attack abilities',
    minplaytime: ' modified states',
    maxplaytime: ' or alternative commander powers.Each robot in the expansion uses an existing game piece.&lt;br/&gt;&lt;br/&gt;These new robots can be included in commander draft',
    age_recommendation: ' or in constructed play',
    complexity: ' and allow for new and different strategies.&lt;br/&gt;&lt;br/&gt;This expansion was previously available as a part of the kickstarter campaign',
    year_published: " but does not come included in the retail base set. In A.E.G.I.S' numbering system",
    more_inf: ' this is &amp;quot;Expansion Set 6&amp;quot;&lt;br/&gt;&lt;br/&gt;"'
  }
]

exports.parseGames = function() {
  return exports.games.map((g, i) => {
    const split = g.split(',')
    return {
      id: split[0],
      bgg_id: split[1],
      title: split[2],
      description: split[3],
      minplayers: split[4],
      maxplayers: split[5],
      minplaytime: split[6],
      maxplaytime: split[7],
      age_recommendation: split[8],
      complexity: split[9],
      year_published: split[10],
      more_info: split[11]
    };
  });
}

exports.stringifyGames = function() {
  exports.games.map((x, i) => {
    return [`${i},${x.bgg_id},"${x.title}","${x.description}",${x.minplayers},${x.maxplayers},${x.minplaytime},${x.maxplaytime},${x.age_recommendation},${x.complexity},${x.year_published},"${x.more_info}"`]
  })
}